### ISSUE TITLE
jhipster microservice box

### ISSUE THREAD

**Issue by jgasmi** [jhipster/jhipster-registry#14]
Really thank you for the new microservice jhipster generator.

I have used it to build a cloud box and I have some notices and issues:
- The gateway microservice generator doesn't include anymore grunt and it's gulp by default
- What about authentication and security, I was expecting to find an authserver microservice option.
- After running my gateway app, I'm not able to get the jhipster welcome page, Is it a Zuul routing issue ?

I have pushed my microservices to https://github.com/jgasmi/jhipster-cloud.

Thank you in advance for any help.

**Comment by xjiaoyang** [comment]
maybe because it is only work with JHipster 3.0, but 3.0 not released yet

**Comment by PierreBesson** [comment]
First thanks for trying it.

>The gateway microservice generator doesn't include anymore grunt and it's gulp by default

Yes this was a team decision to drop Grunt and use only Grunt. If you would really like to have Grunt, please consider doing creating and maintaining a Grunt module. See #https://github.com/jhipster/generator-jhipster/issues/2793.
> What about authentication and security, I was expecting to find an authserver microservice option.

Few things are documented yet on this matter. For security in jhipster microservices, the default is to use a JWT tokens workflow that does not need a central server (if I understand right). There will also be a way to use OAuth2 with [jhipster/jhipster-openid-connect](https://github.com/jhipster/jhipster-openid-connect). I don't think it works for now as the option to use OAuth2 is not present for microservices right now but it will be ready for 3.0.

@jgasmi maybe you can help us test the OAuth2 setup when its integrated in the main generator. @jdubois already did the work but he is very busy so please be patient.

>After running my gateway app, I'm not able to get the jhipster welcome page, Is it a Zuul routing issue ?

It seems to rather be a Gulp issue. When I run gulp in your `jhipster-cloud/jhipster-gateway`. I see:
```
module.js:327
    throw err;
    ^

Error: Cannot find module 'gulp-autoprefixer'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/tmp/jhipster-cloud/jhipster-gateway/gulpfile.js:6:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)

```
This issue has been recently fixed in master. I updated jhipster to the latest master and did a `yo jhipster` in `jhipster-gateway`, overwrited all files and the welcome page is back :smiley:.

**Comment by jdubois** [comment]
Yes for security: I don't think we can have OAuth2 ready for our 3.0 version. We have a POC working, and there isn't any technical issue, but we just don't have enough time for everything.
So OAuth2 should be in a future 3.x release.

**Comment by jgasmi** [comment]
I really appreciate your detailed and quick answers, thank you.

@PierreBesson 
> maybe you can help us test the OAuth2 setup when its integrated in the main generator.

Yes I'm interested to test the OAuth2 setup once implemented.

@jdubois 
> We have a POC working, and there isn't any technical issue.

Do you mean the authserver of the jhipster-experimental-microservices repository ?

**Comment by jdubois** [comment]
Yes, and I started to create the Open ID connect server on https://github.com/jhipster/jhipster-openid-connect
